
all:
	@echo "this is a python script, type \"make run\" to execute"
	
run: 
	python lab3b.py 

clean:
	rm -f lab3b_check.txt *.tar.gz 
	
dist:
	tar -cf lab3b-XXXXXX115-zackmeeks.tar.gz lab3b.py README Makefile